### ISSUE TITLE
Support Proxy Authenication

### ISSUE THREAD

**Issue by JesterEE** [Vladislao/proxy-supervisor#17]
Tried to use a list of proxies that require authentication but could not get it to work:

Proxy server list in the format:
```
protocol://user:password@proxy.server.ext:port
protocol://user:password@proxy.server2.ext:port
```

**Comment by Vladislao** [comment]
Hey @JesterEE 
Took a bit of time, but authentication is [now available](https://github.com/Vladislao/proxy-supervisor?tab=readme-ov-file#authentication)
